local sleepOK = (isClient() or isServer()) and getServerOptions():getBoolean("SleepAllowed") and getServerOptions():getBoolean("SleepNeeded")
ToadTraitsRegistries = {}
---------------------------------------------------------
----                GOOD TRAITS                      ----
---------------------------------------------------------
ToadTraitsRegistries.gunspecialist = CharacterTrait.register("ToadTraits:gunspecialist")
if getActivatedMods():contains("\\1299328280/ToadTraitsDisablePrepared") == false then
    ToadTraitsRegistries.preparedfood = CharacterTrait.register("ToadTraits:preparedfood")
    ToadTraitsRegistries.preparedammo = CharacterTrait.register("ToadTraits:preparedammo")
    ToadTraitsRegistries.preparedmedical = CharacterTrait.register("ToadTraits:preparedmedical")
    ToadTraitsRegistries.preparedrepair = CharacterTrait.register("ToadTraits:preparedrepair")
    ToadTraitsRegistries.preparedcamp = CharacterTrait.register("ToadTraits:preparedcamp")
    ToadTraitsRegistries.preparedweapon = CharacterTrait.register("ToadTraits:preparedweapon")
    ToadTraitsRegistries.preparedpack = CharacterTrait.register("ToadTraits:preparedpack")
    ToadTraitsRegistries.preparedcar = CharacterTrait.register("ToadTraits:preparedcar")
    ToadTraitsRegistries.preparedcoordination = CharacterTrait.register("ToadTraits:preparedcoordination")
end
ToadTraitsRegistries.swift = CharacterTrait.register("ToadTraits:swift")
ToadTraitsRegistries.ingenuitive = CharacterTrait.register("ToadTraits:ingenuitive")
if getActivatedMods():contains("DynamicTraits") == false then
    ToadTraitsRegistries.generator = CharacterTrait.register("ToadTraits:generator")
end
ToadTraitsRegistries.olympian = CharacterTrait.register("ToadTraits:olympian")
ToadTraitsRegistries.bouncer = CharacterTrait.register("ToadTraits:bouncer")
ToadTraitsRegistries.martial = CharacterTrait.register("ToadTraits:martial")
ToadTraitsRegistries.flexible = CharacterTrait.register("ToadTraits:flexible")
ToadTraitsRegistries.grunt = CharacterTrait.register("ToadTraits:grunt")
ToadTraitsRegistries.quiet = CharacterTrait.register("ToadTraits:quiet")
ToadTraitsRegistries.tinkerer = CharacterTrait.register("ToadTraits:tinkerer")
ToadTraitsRegistries.scrapper = CharacterTrait.register("ToadTraits:scrapper")
ToadTraitsRegistries.wildsman = CharacterTrait.register("ToadTraits:wildsman")
ToadTraitsRegistries.natural = CharacterTrait.register("ToadTraits:natural")
ToadTraitsRegistries.bladetwirl = CharacterTrait.register("ToadTraits:bladetwirl")
ToadTraitsRegistries.blunttwirl = CharacterTrait.register("ToadTraits:blunttwirl")
if getActivatedMods():contains("ScavengingSkill") == false and getActivatedMods():contains("ScavengingSkillFixed") == false then
ToadTraitsRegistries.scrounger = CharacterTrait.register("ToadTraits:scrounger")
end
ToadTraitsRegistries.antique = CharacterTrait.register("ToadTraits:antique")
ToadTraitsRegistries.evasive = CharacterTrait.register("ToadTraits:evasive")
ToadTraitsRegistries.blissful = CharacterTrait.register("ToadTraits:blissful")
if getActivatedMods():contains("\\1299328280/ToadTraitsDisableSpec") == false then
    ToadTraitsRegistries.specweapons = CharacterTrait.register("ToadTraits:specweapons")
    ToadTraitsRegistries.speccrafting = CharacterTrait.register("ToadTraits:speccrafting")
    ToadTraitsRegistries.specfood = CharacterTrait.register("ToadTraits:specfood")
    ToadTraitsRegistries.specguns = CharacterTrait.register("ToadTraits:specguns")
    ToadTraitsRegistries.specmove = CharacterTrait.register("ToadTraits:specmove")
    ToadTraitsRegistries.specaid = CharacterTrait.register("ToadTraits:specaid")
end
ToadTraitsRegistries.gordanite = CharacterTrait.register("ToadTraits:gordanite")
ToadTraitsRegistries.indefatigable = CharacterTrait.register("ToadTraits:indefatigable")
ToadTraitsRegistries.hardy = CharacterTrait.register("ToadTraits:hardy")
ToadTraitsRegistries.problunt = CharacterTrait.register("ToadTraits:problunt")
ToadTraitsRegistries.problade = CharacterTrait.register("ToadTraits:problade")
ToadTraitsRegistries.progun = CharacterTrait.register("ToadTraits:progun")
ToadTraitsRegistries.prospear = CharacterTrait.register("ToadTraits:prospear")
ToadTraitsRegistries.actionhero = CharacterTrait.register("ToadTraits:actionhero")
ToadTraitsRegistries.thickblood = CharacterTrait.register("ToadTraits:thickblood")
if getActivatedMods():contains("DrivingSkill") == false then
    ToadTraitsRegistries.expertdriver = CharacterTrait.register("ToadTraits:expertdriver")
end
ToadTraitsRegistries.superimmune = CharacterTrait.register("ToadTraits:superimmune")
ToadTraitsRegistries.packmule = CharacterTrait.register("ToadTraits:packmule")
ToadTraitsRegistries.graverobber = CharacterTrait.register("ToadTraits:graverobber")
ToadTraitsRegistries.gourmand = CharacterTrait.register("ToadTraits:gourmand")
ToadTraitsRegistries.gymgoer = CharacterTrait.register("ToadTraits:gymgoer")
ToadTraitsRegistries.leadfoot = CharacterTrait.register("ToadTraits:leadfoot")
ToadTraitsRegistries.vagabond = CharacterTrait.register("ToadTraits:vagabond")
ToadTraitsRegistries.quickworker = CharacterTrait.register("ToadTraits:quickworker")
ToadTraitsRegistries.batteringram = CharacterTrait.register("ToadTraits:batteringram")
ToadTraitsRegistries.fitted = CharacterTrait.register("ToadTraits:fitted")
ToadTraitsRegistries.tavernbrawler = CharacterTrait.register("ToadTraits:tavernbrawler")
ToadTraitsRegistries.secondwind = CharacterTrait.register("ToadTraits:secondwind")
ToadTraitsRegistries.restfulsleeper = CharacterTrait.register("ToadTraits:restfulsleeper")
ToadTraitsRegistries.noxpshooter = CharacterTrait.register("ToadTraits:noxpshooter")
ToadTraitsRegistries.noxptechnician = CharacterTrait.register("ToadTraits:noxptechnician")
ToadTraitsRegistries.noxpaxe = CharacterTrait.register("ToadTraits:noxpaxe")
ToadTraitsRegistries.noxpfirstaid = CharacterTrait.register("ToadTraits:noxpfirstaid")
ToadTraitsRegistries.noxpmaintenance = CharacterTrait.register("ToadTraits:noxpmaintenance")
ToadTraitsRegistries.noxpsneaky = CharacterTrait.register("ToadTraits:noxpsneaky")
ToadTraitsRegistries.terminator = CharacterTrait.register("ToadTraits:terminator")
ToadTraitsRegistries.unwavering = CharacterTrait.register("ToadTraits:unwavering")
ToadTraitsRegistries.idealweight = CharacterTrait.register("ToadTraits:idealweight")
ToadTraitsRegistries.quickrest = CharacterTrait.register("ToadTraits:quickrest")
---------------------------------------------------------
----                BAD TRAITS                       ----
---------------------------------------------------------
ToadTraitsRegistries.antigun = CharacterTrait.register("ToadTraits:antigun")
ToadTraitsRegistries.noodlelegs = CharacterTrait.register("ToadTraits:noodlelegs")
ToadTraitsRegistries.motionsickness = CharacterTrait.register("ToadTraits:motionsickness")
ToadTraitsRegistries.paranoia = CharacterTrait.register("ToadTraits:paranoia")
ToadTraitsRegistries.packmouse = CharacterTrait.register("ToadTraits:packmouse")
ToadTraitsRegistries.injured = CharacterTrait.register("ToadTraits:injured")
ToadTraitsRegistries.drinker = CharacterTrait.register("ToadTraits:drinker")
ToadTraitsRegistries.broke = CharacterTrait.register("ToadTraits:broke")
ToadTraitsRegistries.butterfingers = CharacterTrait.register("ToadTraits:butterfingers")
ToadTraitsRegistries.incomprehensive = CharacterTrait.register("ToadTraits:incomprehensive")
ToadTraitsRegistries.selfdestructive = CharacterTrait.register("ToadTraits:selfdestructive")
ToadTraitsRegistries.badteeth = CharacterTrait.register("ToadTraits:badteeth")
ToadTraitsRegistries.albino = CharacterTrait.register("ToadTraits:albino")
ToadTraitsRegistries.amputee = CharacterTrait.register("ToadTraits:amputee")
ToadTraitsRegistries.poordriver = CharacterTrait.register("ToadTraits:poordriver")
ToadTraitsRegistries.anemic = CharacterTrait.register("ToadTraits:anemic")
ToadTraitsRegistries.immunocompromised = CharacterTrait.register("ToadTraits:immunocompromised")
ToadTraitsRegistries.ascetic = CharacterTrait.register("ToadTraits:ascetic")
ToadTraitsRegistries.fearful = CharacterTrait.register("ToadTraits:fearful")
ToadTraitsRegistries.glassbody = CharacterTrait.register("ToadTraits:glassbody")
ToadTraitsRegistries.slowworker = CharacterTrait.register("ToadTraits:slowworker")
ToadTraitsRegistries.mundane = CharacterTrait.register("ToadTraits:mundane")
ToadTraitsRegistries.deprived = CharacterTrait.register("ToadTraits:deprived")
ToadTraitsRegistries.burned = CharacterTrait.register("ToadTraits:burned")
--